name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-production:
    name: Deploy to Railway (Production)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install backend dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Railway deploy step rimosso

      # - name: Run smoke tests
      #   run: |
      #     sleep 30
      #     curl -f ${{ secrets.PRODUCTION_API_URL }}/health || exit 1 